## CÓDIGO APENAS PARA CRIAÇÃO DO SCHEMA / TABLE

CREATE DATABASE IF NOT EXISTS user_api;

USE user_api;

CREATE TABLE IF NOT EXISTS users
(
	id INT NOT NULL AUTO_INCREMENT,
	first_name VARCHAR(30) NOT NULL,
	last_name VARCHAR(30) NOT NULL,
	email VARCHAR(30) NOT NULL,
	password VARCHAR(15),
	PRIMARY KEY(id)
);
