version: '3.4'

services:
  mongo:
    image: mongo:5.0.7
    container_name: mongoose_glassesStore
    ports:
      - 27017:27017
    restart: always
    environment:
      - MONGO_DATABASE=${MONGO_DATABASE}
      - MONGO_ROOT_USERNAME=${MONGO_INITDB_MONGO_ROOT_USERNAMEROOT_USERNAME}
      - MONGO_ROOT_PASSWORD=${MONGO_ROOT_PASSWORD}
