## CÓDIGO APENAS PARA CRIAÇÃO DO SCHEMA / TABLE

CREATE DATABASE IF NOT EXISTS cep_api;

USE cep_api;

CREATE TABLE IF NOT EXISTS ceps
(
	cep VARCHAR(9) NOT NULL,
	logradouro VARCHAR(30) NOT NULL,
	bairro VARCHAR(30) NOT NULL,
	localidade VARCHAR(30) NOT NULL,
	uf VARCHAR(5) NOT NULL,
	PRIMARY KEY(cep)
);